/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.ArrayList;
import java.util.Random;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[]args){
        ArrayList array=roll(5);
        System.out.println(containsDuplicates(array));
        System.out.println(average(array));
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        System.out.println(lowestAverage(weeklyMonthTemperatures));
    }
    public static ArrayList roll(int n){
        Random rand=new Random();
        ArrayList result=new ArrayList();
        for(int i=0;i<n;i++){
            result.add(rand.ints(1, 7)
                    .findFirst()
                    .getAsInt());

        }
        return result;

    }

    public static boolean containsDuplicates(ArrayList array){
        System.out.println(array);
        boolean result=false;
        boolean statue=false;
        for(int i=0;i< array.size();i++){
            if(statue){break;}
            for(int j=0;j<array.size();j++){
                if(j!=i&&array.get(i)==array.get(j)){
                    result=true;
                    statue=true;
                    break;
                }
            }
        }
        return result;
    }

    public static double average(ArrayList <Integer>array){
        double sum=0f;
        double average=0f;
        for(int i=0;i<array.size();i++){
            sum=sum+array.get(i);
        }
        return sum/array.size();
    }

    public static double lowestAverage(int [][]array){
        double lowestAverage=1000;
        for(int i=0;i<array.length;i++){
            double sum=0;
            for(int j=0;j<array[i].length;j++){
                sum=sum+array[i][j];
                if(j==array[i].length-1){
                    if(sum/array[i].length<lowestAverage){
                        lowestAverage=sum/array[i].length;
                    }
                }
            }
        }
        return lowestAverage;
    }
}
