/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String []args){
Restaurant alhawen=new Restaurant("alhawen",4,"$");
        System.out.println(alhawen.numbers_of_stars);
 alhawen.addReview("ahmad","nice place",2);
 alhawen.addReview("mohammed","not bad",4);
 Restaurant faheem=new Restaurant("faheem",3,"$$");
faheem.addReview("noor","i dont recommend it",1);
faheem.addReview("noor","i dont recommend it",1);
faheem.addReview("noor","i dont recommend it",1);
        faheem.addReview("noor","i dont recommend it",5);
 System.out.println(alhawen.reviews);
  System.out.println(alhawen.numbers_of_stars);
        System.out.println("-------------");
        System.out.println(faheem.reviews);
        System.out.println(faheem.numbers_of_stars);
    }
}
